### ISSUE TITLE
Question about the result

### ISSUE THREAD

**Issue by shiningliang** [jitinkrishnan/Multilingual-ZeroShot-SlotFilling#1]
Hello, it's a nice and precise work. Thanks for open source at first.
I have a question about the results in Table 3. I noticed that the Slot F1 of modified English-only Baseline are much higher than Xu et al., 2020 especially on non-western languages (eg. hi 77.05 vs 31.21). 
Should I compare the English-only Baseline with No MT for zero-shot in multi ATIS++? Or did I miss anything important of the experimental implementation?

**Comment by jitinkrishnan** [comment]
Good question, the inflation of Slot F1 scores is because we use Micro F1 measure (instead of Macro as used by Xu et al - need verification), to address slot-class imbalance. We plan to add the macro scores as well as we expand the paper. And yes, English-only baseline is equivalent to the No MT in Xu et al. Let me know if that clarified.

**Comment by shiningliang** [comment]
Thanks for your clear reply. And could you please give some insights about which slot labels make the results of micro and macro such different?

**Comment by jitinkrishnan** [comment]
The top/bottom-5 slot classes sorted by count from "train_EN.tsv" and  "train_HI.tsv" dataset of MultiAtis++ are shown below. We can see that they vary a lot and do not stay the same across languages. Macro calculates f1 for each label and then find their unweighted mean. So, I think, if we want to give more importance to the classes with lower counts, we would need to use Macro - so generally this produces lower scores as compared to micro because classifiers typically learn to classify the classes with more samples better. In the paper by Xu et al, not sure if it is explicitly mentioned whether its macro or micro. So we reproduced the model and used Micro for all our experiments to be consistent across. If their scores are in fact Micro, I can look into their code (once its public), to check for differences in implementations that may cause this discrepancy for non-western languages. Hope this helps :)
```
English:
[('stoploc.airport_name', 1),
 ('return_date.day_name', 1),
 ('time_relative', 1),
 ('arrive_date.today_relative', 2),
 ('return_time.period_mod', 2),
... 
 ('depart_date.day_name', 798),
 ('airline_name', 1004),
 ('fromloc.city_name', 4520),
 ('toloc.city_name', 4925),
 ('O', 32225)]

Hindi:
[('toloc.country_name', 1),
 ('return_date.day_number', 1),
 ('return_date.month_name', 1),
 ('stoploc.airport_name', 1),
 ('state_name', 1),
 ...
 ('depart_date.day_name', 256),
 ('airline_name', 277),
 ('fromloc.city_name', 1461),
 ('toloc.city_name', 1542),
 ('O', 11185)]
```
